export const questions = {
  decks: [
    {
      name: 'RIASEC Interests',
      description: 'Each option is tagged with one or more Holland RIASEC interest codes.',
      questions: [
        {
          id: 1,
          option1: {
            id: 'riasec-bike-repair',
            text: 'Build and repair a bicycle',
            prompt: 'A young adult building and repairing a bicycle in a workshop',
            codes: ['R'],
            imageUrl: '/would-you-rather/images/riasec-bike-repair.png',
          },
          option2: {
            id: 'riasec-comic-art',
            text: 'Write and illustrate a comic',
            prompt: 'A creative person writing and drawing illustrations for a comic book',
            codes: ['A'],
            imageUrl: '/would-you-rather/images/riasec-comic-art.png',
          },
        },
        {
          id: 2,
          option1: {
            id: 'riasec-chemistry-lab',
            text: 'Mix chemicals to see what happens',
            prompt: 'A curious student conducting chemistry experiments in a laboratory',
            codes: ['I'],
            imageUrl: '/would-you-rather/images/riasec-chemistry-lab.png',
          },
          option2: {
            id: 'riasec-fundraiser',
            text: 'Run a school-wide fundraiser and persuade donors',
            prompt: 'A confident student presenting to potential donors at a school fundraiser',
            codes: ['E'],
            imageUrl: '/would-you-rather/images/riasec-fundraiser.png',
          },
        },
        {
          id: 3,
          option1: {
            id: 'riasec-digital-design',
            text: 'Design a digital poster from scratch',
            prompt: 'A creative designer working on a digital poster using design software',
            codes: ['A'],
            imageUrl: '/would-you-rather/images/riasec-digital-design.png',
          },
          option2: {
            id: 'riasec-math-tutor',
            text: 'Tutor a friend in math',
            prompt: 'A patient student helping a friend understand math problems',
            codes: ['S'],
            imageUrl: '/would-you-rather/images/riasec-math-tutor.png',
          },
        },
        {
          id: 4,
          option1: {
            id: 'riasec-budget-spreadsheet',
            text: 'Keep the club\'s budget in a spreadsheet',
            prompt: 'A detail-oriented student managing financial records in a spreadsheet',
            codes: ['C'],
            imageUrl: '/would-you-rather/images/riasec-budget-spreadsheet.png',
          },
          option2: {
            id: 'riasec-club-debate',
            text: 'Debate ideas for a brand-new student club',
            prompt: 'A group of students passionately discussing ideas for a new club',
            codes: ['E'],
            imageUrl: '/would-you-rather/images/riasec-club-debate.png',
          },
        },
        {
          id: 5,
          option1: {
            id: 'riasec-plant-experiment',
            text: 'Investigate why certain plants grow faster under colored lights',
            prompt: 'A curious student conducting a plant growth experiment with colored lights',
            codes: ['I'],
            imageUrl: '/would-you-rather/images/riasec-plant-experiment.png',
          },
          option2: {
            id: 'riasec-sports-coach',
            text: 'Coach a younger sports team',
            prompt: 'A supportive student coaching and encouraging younger athletes',
            codes: ['S'],
            imageUrl: '/would-you-rather/images/riasec-sports-coach.png',
          },
        },
        {
          id: 6,
          option1: {
            id: 'riasec-3d-printing',
            text: 'Operate a 3-D printer to make prototypes',
            prompt: 'A tech-savvy student operating a 3D printer to create prototypes',
            codes: ['R'],
            imageUrl: '/would-you-rather/images/riasec-3d-printing.png',
          },
          option2: {
            id: 'riasec-library-catalog',
            text: 'Catalog library books by call number',
            prompt: 'A methodical student organizing and cataloging books in a library',
            codes: ['C'],
            imageUrl: '/would-you-rather/images/riasec-library-catalog.png',
          },
        },
        {
          id: 7,
          option1: {
            id: 'riasec-film-director',
            text: 'Direct a short film with your friends',
            prompt: 'A creative student directing friends in a short film production',
            codes: ['A'],
            imageUrl: '/would-you-rather/images/riasec-film-director.png',
          },
          option2: {
            id: 'riasec-product-pitch',
            text: 'Pitch a new product idea to classmates',
            prompt: 'A confident student presenting a product idea to classmates',
            codes: ['E'],
            imageUrl: '/would-you-rather/images/riasec-product-pitch.png',
          },
        },
        {
          id: 8,
          option1: {
            id: 'riasec-logic-puzzle',
            text: 'Solve a detective-style logic puzzle',
            prompt: 'A focused student solving a complex logic puzzle',
            codes: ['I'],
            imageUrl: '/would-you-rather/images/riasec-logic-puzzle.png',
          },
          option2: {
            id: 'riasec-student-mentor',
            text: 'Mentor new students to help them feel welcome',
            prompt: 'A friendly student helping new students feel welcome at school',
            codes: ['S'],
            imageUrl: '/would-you-rather/images/riasec-student-mentor.png',
          },
        },
        {
          id: 9,
          option1: {
            id: 'riasec-network-setup',
            text: 'Set up the school\'s Wi-Fi network',
            prompt: 'A technical student configuring and setting up a school network',
            codes: ['R'],
            imageUrl: '/would-you-rather/images/riasec-network-setup.png',
          },
          option2: {
            id: 'riasec-event-budget',
            text: 'Create a detailed budget for an event',
            prompt: 'A detail-oriented student planning a detailed event budget',
            codes: ['C'],
            imageUrl: '/would-you-rather/images/riasec-event-budget.png',
          },
        },
        {
          id: 10,
          option1: {
            id: 'riasec-board-game-teach',
            text: 'Teach a group how to play a board game',
            prompt: 'A patient student teaching a group how to play a board game',
            codes: ['S'],
            imageUrl: '/would-you-rather/images/riasec-board-game-teach.png',
          },
          option2: {
            id: 'riasec-game-rules',
            text: 'Write the official rules and scoring sheet',
            prompt: 'A detail-oriented student writing clear game rules and scoring guidelines',
            codes: ['C'],
            imageUrl: '/would-you-rather/images/riasec-game-rules.png',
          },
        },
      ],
    },
    {
      name: 'Work-Value Motivators',
      description: 'Options are tagged with O*NET work-value codes: ACH, IND, REC, REL, SUP, WC.',
      questions: [
        {
          id: 1,
          option1: {
            id: 'workvalue-award-win',
            text: 'Win an award for top performance',
            prompt: 'A proud professional receiving recognition for outstanding work',
            codes: ['REC'],
            imageUrl: '/would-you-rather/images/workvalue-award-win.png',
          },
          option2: {
            id: 'workvalue-life-impact',
            text: 'See your work improve people\'s lives each day',
            prompt: 'A caring professional seeing the positive impact of their work on others',
            codes: ['REL'],
            imageUrl: '/would-you-rather/images/workvalue-life-impact.png',
          },
        },
        {
          id: 2,
          option1: {
            id: 'workvalue-flex-schedule',
            text: 'Set your own schedule',
            prompt: 'A professional managing their own flexible work schedule',
            codes: ['IND'],
            imageUrl: '/would-you-rather/images/workvalue-flex-schedule.png',
          },
          option2: {
            id: 'workvalue-mentor-guidance',
            text: 'Have a mentor who guides you step-by-step',
            prompt: 'A professional receiving guidance from an experienced mentor',
            codes: ['SUP'],
            imageUrl: '/would-you-rather/images/workvalue-mentor-guidance.png',
          },
        },
        {
          id: 3,
          option1: {
            id: 'workvalue-high-salary',
            text: 'Earn a high salary for hitting tough goals',
            prompt: 'A motivated professional achieving challenging goals for financial reward',
            codes: ['ACH'],
            imageUrl: '/would-you-rather/images/workvalue-high-salary.png',
          },
          option2: {
            id: 'workvalue-modern-office',
            text: 'Work in a modern office with great equipment',
            prompt: 'A professional working in a well-equipped modern office space',
            codes: ['WC'],
            imageUrl: '/would-you-rather/images/workvalue-modern-office.png',
          },
        },
        {
          id: 4,
          option1: {
            id: 'workvalue-skill-growth',
            text: 'Take on challenging tasks that grow your skills',
            prompt: 'A professional tackling challenging projects to develop new skills',
            codes: ['ACH'],
            imageUrl: '/would-you-rather/images/workvalue-skill-growth.png',
          },
          option2: {
            id: 'workvalue-creative-praise',
            text: 'Receive public praise for creative ideas',
            prompt: 'A creative professional receiving recognition for innovative ideas',
            codes: ['REC'],
            imageUrl: '/would-you-rather/images/workvalue-creative-praise.png',
          },
        },
        {
          id: 5,
          option1: {
            id: 'workvalue-project-choice',
            text: 'Choose which project to tackle next',
            prompt: 'A professional selecting their next project independently',
            codes: ['IND'],
            imageUrl: '/would-you-rather/images/workvalue-project-choice.png',
          },
          option2: {
            id: 'workvalue-team-collab',
            text: 'Collaborate daily with close teammates',
            prompt: 'A professional working closely with a supportive team',
            codes: ['REL'],
            imageUrl: '/would-you-rather/images/workvalue-team-collab.png',
          },
        },
        {
          id: 6,
          option1: {
            id: 'workvalue-job-security',
            text: 'Have steady health-benefit coverage and job security',
            prompt: 'A professional enjoying stable employment with good benefits',
            codes: ['SUP'],
            imageUrl: '/would-you-rather/images/workvalue-job-security.png',
          },
          option2: {
            id: 'workvalue-team-lead',
            text: 'Lead a team to beat an ambitious target',
            prompt: 'A professional leading a team to achieve challenging goals',
            codes: ['ACH'],
            imageUrl: '/would-you-rather/images/workvalue-team-lead.png',
          },
        },
        {
          id: 7,
          option1: {
            id: 'workvalue-stage-recognition',
            text: 'Be spotlighted on stage for your successes',
            prompt: 'A professional receiving public recognition for their achievements',
            codes: ['REC'],
            imageUrl: '/would-you-rather/images/workvalue-stage-recognition.png',
          },
          option2: {
            id: 'workvalue-quiet-space',
            text: 'Enjoy a calm, quiet workspace with few distractions',
            prompt: 'A professional working in a peaceful, focused environment',
            codes: ['WC'],
            imageUrl: '/would-you-rather/images/workvalue-quiet-space.png',
          },
        },
        {
          id: 8,
          option1: {
            id: 'workvalue-outdoor-work',
            text: 'Work outdoors in all kinds of weather',
            prompt: 'A professional working in various outdoor conditions',
            codes: ['WC'],
            imageUrl: '/would-you-rather/images/workvalue-outdoor-work.png',
          },
          option2: {
            id: 'workvalue-coworker-help',
            text: 'Help coworkers solve personal challenges',
            prompt: 'A supportive professional helping colleagues with their challenges',
            codes: ['REL'],
            imageUrl: '/would-you-rather/images/workvalue-coworker-help.png',
          },
        },
        {
          id: 9,
          option1: {
            id: 'workvalue-flex-workflow',
            text: 'Design your own workflow with minimal rules',
            prompt: 'A professional creating their own flexible work process',
            codes: ['IND'],
            imageUrl: '/would-you-rather/images/workvalue-flex-workflow.png',
          },
          option2: {
            id: 'workvalue-structured-guidance',
            text: 'Rely on clear instructions and supportive check-ins',
            prompt: 'A professional following structured guidance with regular support',
            codes: ['SUP'],
            imageUrl: '/would-you-rather/images/workvalue-structured-guidance.png',
          },
        },
        {
          id: 10,
          option1: {
            id: 'workvalue-goal-progress',
            text: 'Reach difficult milestones and see measurable progress',
            prompt: 'A professional achieving challenging goals with clear progress',
            codes: ['ACH'],
            imageUrl: '/would-you-rather/images/workvalue-goal-progress.png',
          },
          option2: {
            id: 'workvalue-leader-recognition',
            text: 'Feel appreciated and thanked by leadership',
            prompt: 'A professional receiving gratitude and recognition from leaders',
            codes: ['REC'],
            imageUrl: '/would-you-rather/images/workvalue-leader-recognition.png',
          },
        },
      ],
    },
    {
      name: 'Workplace-Environment Preferences',
      description: 'Options are tagged with environment codes: INO, OUT, RT, VR, TM, SO.',
      questions: [
        {
          id: 1,
          option1: {
            id: 'env-air-conditioned',
            text: 'Work at a laptop in an air-conditioned room',
            prompt: 'A professional working comfortably at a laptop in a climate-controlled office',
            codes: ['INO'],
            imageUrl: '/would-you-rather/images/env-air-conditioned.png',
          },
          option2: {
            id: 'env-outdoor-fresh',
            text: 'Work outside in the fresh air',
            prompt: 'A professional working outdoors in a natural environment',
            codes: ['OUT'],
            imageUrl: '/would-you-rather/images/env-outdoor-fresh.png',
          },
        },
        {
          id: 2,
          option1: {
            id: 'env-daily-checklist',
            text: 'Follow a clear daily checklist',
            prompt: 'A professional following a structured daily routine',
            codes: ['RT'],
            imageUrl: '/would-you-rather/images/env-daily-checklist.png',
          },
          option2: {
            id: 'env-daily-surprises',
            text: 'Face new surprises every day',
            prompt: 'A professional adapting to unexpected challenges daily',
            codes: ['VR'],
            imageUrl: '/would-you-rather/images/env-daily-surprises.png',
          },
        },
        {
          id: 3,
          option1: {
            id: 'env-group-collab',
            text: 'Collaborate with a big group on projects',
            prompt: 'A professional working with a large team on collaborative projects',
            codes: ['TM'],
            imageUrl: '/would-you-rather/images/env-group-collab.png',
          },
          option2: {
            id: 'env-solo-focus',
            text: 'Focus quietly on tasks by yourself',
            prompt: 'A professional working independently in a quiet space',
            codes: ['SO'],
            imageUrl: '/would-you-rather/images/env-solo-focus.png',
          },
        },
        {
          id: 4,
          option1: {
            id: 'env-consistent-desk',
            text: 'Have the same desk and hours all year',
            prompt: 'A professional working at a consistent location with regular hours',
            codes: ['RT'],
            imageUrl: '/would-you-rather/images/env-consistent-desk.png',
          },
          option2: {
            id: 'env-travel-sites',
            text: 'Travel to different sites each week',
            prompt: 'A professional traveling to various locations for work',
            codes: ['VR'],
            imageUrl: '/would-you-rather/images/env-travel-sites.png',
          },
        },
        {
          id: 5,
          option1: {
            id: 'env-open-office',
            text: 'Brainstorm ideas in a buzzing open office',
            prompt: 'A professional collaborating in a lively open office environment',
            codes: ['TM'],
            imageUrl: '/would-you-rather/images/env-open-office.png',
          },
          option2: {
            id: 'env-independent-pace',
            text: 'Solve problems independently at your own pace',
            prompt: 'A professional working alone at their preferred speed',
            codes: ['SO'],
            imageUrl: '/would-you-rather/images/env-independent-pace.png',
          },
        },
        {
          id: 6,
          option1: {
            id: 'env-wildlife-study',
            text: 'Inspect wildlife habitats in the field',
            prompt: 'A professional studying wildlife in their natural habitats',
            codes: ['OUT'],
            imageUrl: '/would-you-rather/images/env-wildlife-study.png',
          },
          option2: {
            id: 'env-data-analysis',
            text: 'Analyze data charts in a conference room',
            prompt: 'A professional analyzing data in a formal meeting space',
            codes: ['INO'],
            imageUrl: '/would-you-rather/images/env-data-analysis.png',
          },
        },
        {
          id: 7,
          option1: {
            id: 'env-inventory-log',
            text: 'Check inventory and log numbers each hour',
            prompt: 'A professional maintaining detailed inventory records',
            codes: ['RT'],
            imageUrl: '/would-you-rather/images/env-inventory-log.png',
          },
          option2: {
            id: 'env-fast-tasks',
            text: 'Juggle many small, fast-moving tasks',
            prompt: 'A professional managing multiple quick tasks simultaneously',
            codes: ['VR'],
            imageUrl: '/would-you-rather/images/env-fast-tasks.png',
          },
        },
        {
          id: 8,
          option1: {
            id: 'env-team-meetings',
            text: 'Lead daily stand-up meetings with the crew',
            prompt: 'A professional conducting daily team meetings',
            codes: ['TM'],
            imageUrl: '/would-you-rather/images/env-team-meetings.png',
          },
          option2: {
            id: 'env-quiet-research',
            text: 'Research quietly without interruption',
            prompt: 'A professional conducting focused research in solitude',
            codes: ['SO'],
            imageUrl: '/would-you-rather/images/env-quiet-research.png',
          },
        },
        {
          id: 9,
          option1: {
            id: 'env-soil-samples',
            text: 'Collect soil samples for a science study',
            prompt: 'A professional gathering environmental samples outdoors',
            codes: ['OUT'],
            imageUrl: '/would-you-rather/images/env-soil-samples.png',
          },
          option2: {
            id: 'env-digital-present',
            text: 'Design presentations on a computer',
            prompt: 'A professional creating digital presentations indoors',
            codes: ['INO'],
            imageUrl: '/would-you-rather/images/env-digital-present.png',
          },
        },
        {
          id: 10,
          option1: {
            id: 'env-role-rotation',
            text: 'Rotate through different roles every semester',
            prompt: 'A professional experiencing various job roles regularly',
            codes: ['VR'],
            imageUrl: '/would-you-rather/images/env-role-rotation.png',
          },
          option2: {
            id: 'env-specialized-role',
            text: 'Master one role and stick with it',
            prompt: 'A professional specializing in a single role long-term',
            codes: ['RT'],
            imageUrl: '/would-you-rather/images/env-specialized-role.png',
          },
        },
      ],
    },
  ],
}

const 

