import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import Link from 'next/link'
import { ClerkProvider, SignedIn, SignedOut, SignInButton, UserButton } from '@clerk/nextjs'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    // <ClerkProvider>
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="navbar p-0 bg-base-100 shadow-sm">
          <div className="container flex flex-row items-center mx-auto max-w-4xl">

            <div className="flex-1">
              <Link href="/" className="btn btn-ghost btn-link no-underline  p-1 text-xl text-nowrap">Career Quest</Link>
            </div>
            <div className="flex flex-row items-center gap-1">
              {/* <SignedOut>
                  {/* @ts-expect-error className is not a prop of SignInButton */}
              {/* <SignInButton className="btn btn-primary" mode="modal" />
                </SignedOut> */}
              {/* <SignedIn> */}
              <div className="dropdown dropdown-end md:hidden">
                <div tabIndex={0} role="button" className="btn btn-ghost">
                  <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M4 6h16M4 12h16M4 18h16" />
                  </svg>
                </div>
                <ul tabIndex={0} className="dropdown-content z-[1] menu p-2 shadow bg-base-100 rounded-box w-52">
                  <li><Link href="/intake/interests">Interests</Link></li>
                  <li><Link href="/intake/would-you-rather">Would You Rather</Link></li>
                  <li><Link href="/intake/summary">Summary</Link></li>
                  <li><Link href="/careers">Careers</Link></li>
                </ul>
              </div>
              <ul className="menu menu-horizontal px-1 hidden md:flex">
                <li><Link href="/intake/interests">Interests</Link></li>
                <li><Link href="/intake/would-you-rather">Would You Rather</Link></li>
                <li><Link href="/intake/summary">Summary</Link></li>
                <li><Link href="/careers">Careers</Link></li>
              </ul>
              {/* <div className="max-h-7">
                    <UserButton />
                  </div> */}
              {/* </SignedIn> */}

            </div>
          </div>
        </nav>

        {children}

      </body>
    </html>
    // </ClerkProvider>

  )
}
